try SUBLIME as a core editor
There was an error that occured before properly configuring the editor

error: hint: Waiting for your editor to close the file... 'C:\Program Files\Sublime Text 3\sublime_text.exe' -w: C:\Program Files\Sublime Text 3\sublime_text.exe: No such file or directory
error: There was a problem with the editor ''C:\Program Files\Sublime Text 3\sublime_text.exe' -w'.
Please supply the message using either -m or -F option.

solution: I replace the PATH for the SUBLIME editor to the one where it is currently place, as this editor is a cracked version; C:\Users\ArKaDQta\Downloads\Programs\Sublime Text\sublime_text.exe

now I can use git commit and open SUBLIME as an editor for the message instead of VIM